### ISSUE TITLE
feature request: add record-deployment

### ISSUE THREAD

**Issue by YOU54F** [pactflow/actions#4]

**Comment by bethesque** [comment]
Love all these actions! The one thing I have noticed is that the actions use `pact_broker` while the CLI uses `PACT_BROKER_BASE_URL` (btw, I very much wish I'd used just `PACT_BROKER_URL` when I wrote all that code). What are your thoughts on the mismatch Yousaf?

**Comment by YOU54F** [comment]
it jars me a little

the naming gets hard I think

https://github.com/pact-foundation/pact_broker-client#record-deployment

Take this

```
  -b, --broker-base-url=BROKER_BASE_URL
              # The base URL of the Pact Broker
  -u, [--broker-username=BROKER_USERNAME]
              # Pact Broker basic auth username
  -p, [--broker-password=BROKER_PASSWORD]
              # Pact Broker basic auth password
  -k, [--broker-token=BROKER_TOKEN]
              # Pact Broker bearer token
```

Now if we have an env vars set for `PACT_BROKER_BASE_URL` / `PACT_BROKER_TOKEN`, I believe they are picked up by the CLI automatically?

Would I call it

- `broker-base-url`
- `BROKER_BASE_URL`
- `PACT_BROKER_BASE_URL`
- `pact_broker`

First feels right and then if you need to pass it into the CLI tool, you take the option in the GH actions and pop `--` before it

I'm happy to go though and rename these for alignment to get parity across the board

**Comment by bethesque** [comment]
> Now if we have an env vars set for PACT_BROKER_BASE_URL / PACT_BROKER_TOKEN, I believe they are picked up by the CLI automatically?

Yes

Ugh, I'd forgotten about the "broker" prefix of the CLI. That bugs me a lot. If I was going to start again it would be `--pact-broker-url` and `PACT_BROKER_URL`. But it would take more time/effort/confusion to standardise everything now than it is worth, I think.

Just doing a bit of a search on the pact-foundation codebases, we have 

* [140 references to `PACT_BROKER_BASE_URL`](https://github.com/search?q=org%3Apact-foundation+PACT_BROKER_BASE_URL&type=code) (all these are ignoring case) and [2 references to `pactBrokerBaseUrl`](https://github.com/search?q=org%3Apact-foundation+pactbrokerbaseurl&type=code)
* [13 references to `PACT_BROKER_URL`](https://github.com/search?q=org%3Apact-foundation+PACT_BROKER_URL&type=code) and [38 references to pactBrokerUrl](https://github.com/search?q=org%3Apact-foundation+pactbrokerurl&type=code)
* [48 references to `BROKER_BASE_URL`](https://github.com/search?q=org%3Apact-foundation+BROKER_BASE_URL&type=code) and [0 references to `brokerBaseUrl`](https://github.com/search?q=org%3Apact-foundation+brokerbaseurl&type=code)
* [19 references to `BROKER_URL`](https://github.com/search?q=org%3Apact-foundation+BROKER_URL&type=code) and [24 references to `brokerUrl`](https://github.com/search?q=org%3Apact-foundation+brokerurl&type=code)

Oh joy!

**Comment by bethesque** [comment]
I'm happy to update all the cli commands to use `--pact-broker-x` and alias them to the old names, and use `--pact-broker-url` instead of base-url. It's still going to cause a bit of pain though, as the docs are not very good at identifying which version they belong to.

I think for these actions, it would be the most consistent with the current recommended usage to use `PACT_BROKER_BASE_URL` and `PACT_BROKER_TOKEN` env vars. They're generally going to be set from some secrets management place anyway.

**Comment by YOU54F** [comment]
renamed now to `PACT_BROKER_BASE_URL` and `PACT_BROKER_TOKEN` and setup a CI pipeline for running the unit tests and set up some e2e tests to test out a flow with the actions 👍🏾 

Need to sort out the release process as its manual at the moment - just create a release tag from master, but it'll do for now :)
