### ISSUE TITLE
feat: Support setting the OAS content type in publish provider contract action

### ISSUE THREAD

**Issue by matteus6007** [pactflow/actions#43]
In the `publish-provider-contract` action the `content-type` is hard coded to `application/yaml`, currently the API I am using only has an `application/json` openapi contract.

I am happy to submit a PR to add this functionality, please let me know the process for contributing to the repo.

**Comment by YOU54F** [comment]
I believe despite it being hard coded it is tolerant to you uploading a valid oas which is in json format. have you tried?

if you do want to submit a pr to ascertain the content type based on say the file extension, feel free to propose a pull request by forking the repo.

we normally communicate change intent via commit messages, you can check previous commit history for examples.
