### ISSUE TITLE
Tags env var not honored in publish-pact-files action

### ISSUE THREAD

**Issue by PH1P5** [pactflow/actions#44]
### Actual
The documentation of the [publish-pact-files](https://github.com/pactflow/actions/blob/main/publish-pact-files/README.md) action suggests to use _tags_ as environment variable:

`// docu says:
  env:
    tags: ...
`

Instead of _tags_ the variable _tag_ is used in the script

### Expected
The documentation is aligned with the script

**Comment by YOU54F** [comment]
Updated docs now, ty
