### ISSUE TITLE
Dubious about pact-can-i-deploy-latest

### ISSUE THREAD

**Issue by bethesque** [pactflow/actions#9]
I never recommend doing this because it's liable to all sorts of race conditions. Can we drop support for this?

**Comment by bethesque** [comment]
Ok, just realised it's an example. Can we remove this example? I really wouldn't want people doing that.

For the pact-can-i-move-upstream example, it's worth adding a comment to note that the `latest: stage` is a tag, not an environment. I'm a bit dubious about recommending that usage too, but I guess deployments happen less frequently than builds, so it's less likely to suffer from race conditions.

**Comment by YOU54F** [comment]
removed both examples for now, to avoid recommending it without caveats and it is not our recommended setup anyway so makes sense

**Comment by bethesque** [comment]
Thanks 🦆 :)
